apiVersion: config.porch.kpt.dev/v1alpha1
kind: RemoteRootSyncSet
metadata: # kpt-merge: example/porch-install
  name: porch-install
  namespace: dev
  annotations:
    internal.kpt.dev/upstream-identifier: 'config.porch.kpt.dev|RemoteRootSyncSet|example|porch-install'
spec:
  clusterRefs:
  - apiVersion: container.cnrm.cloud.google.com/v1beta1
    kind: ContainerCluster
    name: us-central1
    namespace: dev
  template:
    sourceFormat: unstructured
    oci:
      repository: gcr.io/yuwenma-gke-catalyst-goog-rlol/porch:v0.1
