apiVersion: config.porch.kpt.dev/v1alpha1
kind: RootSyncSet
metadata: # kpt-merge: example/porch-install
  name: porch-install
  namespace: example
  annotations:
    internal.kpt.dev/upstream-identifier: 'config.porch.kpt.dev|RootSyncSet|example|porch-install'
spec:
  clusterRefs:
  - apiVersion: container.cnrm.cloud.google.com/v1beta1
    kind: ContainerCluster
    name: us-central1
    namespace: example
  template:
    spec:
      sourceFormat: unstructured
      git:
        auth: none
        repo: http://github.com/yourldap/kpt.git
        # branch: main # YOUR FEATURE BRANCH i.e. verify-workload-identity
        dir: porch/deployments/porch # Please update this to contain your local builds
